Repository Basicbug/Bikini_Android, pull requests merged in 2020-11, with the labels that each got.

#14 네트워크 구성
  app/src/main/java/com/example/bikini_android/app/AppResources.kt
  app/src/main/java/com/example/bikini_android/app/BikiniApp.kt
  app/src/main/java/com/example/bikini_android/network/NetworkConstants.kt
  app/src/main/java/com/example/bikini_android/network/client/ApiClient.kt
  app/src/main/java/com/example/bikini_android/network/client/ApiClientHelper.kt
  app/src/main/java/com/example/bikini_android/network/client/ApiFactory.kt
  app/src/main/java/com/example/bikini_android/network/client/BikiniDebugApiClient.kt
  app/src/main/java/com/example/bikini_android/network/client/BikiniDefaultApiClient.kt
  app/src/main/java/com/example/bikini_android/network/client/BikiniLoggingApiClient.kt
  app/src/main/java/com/example/bikini_android/network/client/RestApiClient.kt
  app/src/main/java/com/example/bikini_android/network/request/param/RestApiParameter.kt
  app/src/main/java/com/example/bikini_android/network/request/param/RestApiParameterKey.kt
  app/src/main/java/com/example/bikini_android/network/request/param/SampleParameter.kt
  app/src/main/java/com/example/bikini_android/network/request/service/SampleService.kt
  app/src/main/java/com/example/bikini_android/network/response/JsonResponse.kt
  app/src/main/java/com/example/bikini_android/network/response/JsonResponseWrapper.kt
  app/src/main/java/com/example/bikini_android/network/response/RestApiMessage.kt
  app/src/main/java/com/example/bikini_android/network/response/SampleResponse.kt
Labels: 구조

#15 main holder 구성
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/bikini_android/MainActivity.kt
  app/src/main/java/com/example/bikini_android/ui/adding/feed/AddingFeedFragment.kt
  app/src/main/java/com/example/bikini_android/ui/base/BaseActivity.kt
  app/src/main/java/com/example/bikini_android/ui/base/BaseFragment.kt
  app/src/main/java/com/example/bikini_android/ui/holder/BottomNavigationItem.kt
  app/src/main/java/com/example/bikini_android/ui/holder/MainHolderActivity.kt
  app/src/main/java/com/example/bikini_android/ui/holder/MainHolderFragment.kt
  app/src/main/java/com/example/bikini_android/ui/holder/NavigationController.kt
  app/src/main/java/com/example/bikini_android/ui/map/BikiniMapFragment.kt
  app/src/main/java/com/example/bikini_android/ui/settings/SettingsFragment.kt
  app/src/main/res/color/bottom_navigation_selector.xml
  app/src/main/res/drawable/bottom_bikini_map_icon.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_main_holder.xml
  app/src/main/res/layout/fragment_adding_feed.xml
  app/src/main/res/layout/fragment_bikini_map.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/menu/bottom_navigation_item.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 구조, 기능

#19 item view model 추가
  app/src/main/java/com/example/bikini_android/ui/common/BindableLayout.kt
  app/src/main/java/com/example/bikini_android/ui/common/ItemViewModel.kt
Labels: 구조

#23 다크, 라이트 테마 적용
  app/src/main/res/color/bottom_navigation_selector.xml
  app/src/main/res/layout/activity_main_holder.xml
  app/src/main/res/layout/fragment_bikini_map.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
Labels: 구조, 기능

#25 툴바 작업
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/bikini_android/ui/common/ToolbarItem.kt
  app/src/main/java/com/example/bikini_android/ui/holder/BottomNavigationItem.kt
  app/src/main/java/com/example/bikini_android/ui/holder/MainHolderActivity.kt
  app/src/main/java/com/example/bikini_android/ui/map/BikiniMapFragment.kt
  app/src/main/java/com/example/bikini_android/ui/settings/SettingsFragment.kt
  app/src/main/java/com/example/bikini_android/util/logging/Logger.kt
  app/src/main/res/layout/activity_main_holder.xml
  app/src/main/res/layout/fragment_bikini_map.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 구조, 기능

#21 Settings Fragment 기본 레이아웃 추가
  app/src/main/java/com/example/bikini_android/ui/settings/SettingsFragment.kt
  app/src/main/java/com/example/bikini_android/util/ktx/ActivityExt.kt
  app/src/main/res/xml/preference_settings_main.xml
  libraries.gradle
Labels: 구조

#28 글라이드 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/bikini_android/app/BikiniGlideModule.kt
  app/src/main/java/com/example/bikini_android/ui/databinding/ImageBindingAdapter.kt
  app/src/main/res/layout/fragment_bikini_map.xml
Labels: 구조

#32 Fix toolbar color 수정
  app/src/main/res/layout/activity_main_holder.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: bug

#35 툴바 이벤트 발생 시에 타이밍 이슈와 코드 중복 처리
  app/src/main/java/com/example/bikini_android/ui/holder/MainHolderActivity.kt
Labels: bug

#36 1차 map 정리
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/bikini_android/ui/base/BaseActivity.kt
  app/src/main/java/com/example/bikini_android/ui/base/BaseFragment.kt
  app/src/main/java/com/example/bikini_android/ui/base/BaseMapFragment.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/FeedsFragment.kt
  app/src/main/java/com/example/bikini_android/ui/holder/MainHolderFragment.kt
  app/src/main/java/com/example/bikini_android/ui/map/BikiniMapFragment.kt
  app/src/main/java/com/example/bikini_android/util/bus/event/LocationPermissionEvent.kt
  app/src/main/java/com/example/bikini_android/util/permission/OnPermissionCallback.kt
  app/src/main/java/com/example/bikini_android/util/permission/PermissionUtils.kt
  app/src/main/res/layout/activity_main_holder.xml
  app/src/main/res/layout/fragment_bikini_map.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  libraries.gradle
Labels: 기능

#38 Fix 네비게이트 이용시에 무한루프 도는 현상 수정
  app/src/main/java/com/example/bikini_android/ui/holder/MainHolderActivity.kt
Labels: bug
