Repository Basicbug/Bikini_Android, pull requests merged in 2021-04, with the labels that each got.

#128 Fix #127 난독화 오류 픽스
  app/proguard-rules.pro
  app/src/main/java/com/example/bikini_android/repository/feed/Feed.kt
  app/src/main/java/com/example/bikini_android/repository/feed/LocationInfo.kt
Labels: bug

#133 #112 송수신 에러 발생시에 동일하게 에러 및 로그 처리
  app/src/main/java/com/example/bikini_android/repository/feed/FeedRepository.kt
  app/src/main/java/com/example/bikini_android/repository/feed/FeedRepositoryImpl.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/LoadAllFeedsUseCase.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/LoadMyFeedsUseCase.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/LoadNearbyFeedsUseCase.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/LoadRankingFeedsUseCase.kt
  app/src/main/java/com/example/bikini_android/util/error/ErrorToastHelper.kt
  app/src/main/res/values/strings.xml
Labels: 기능

#131 Flipper 세팅
  app/build.gradle
  app/src/debug/java/com/example/bikini_android/ui/settings/FlipperSettingImpl.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/bikini_android/network/HostSelectionInterceptor.kt
  app/src/main/java/com/example/bikini_android/network/client/RestApiClient.kt
  app/src/release/java/com/example/bikini_android/ui/settings/FlipperSettingImpl.kt
  libraries.gradle
Labels: 구조

#136 [#135] 오토클리어 사용
  app/build.gradle
  app/src/main/java/com/example/bikini_android/ui/feeds/FeedsFragment.kt
  app/src/main/java/com/example/bikini_android/ui/map/BikiniMapFragment.kt
  app/src/main/java/com/example/bikini_android/ui/profile/ProfileFragment.kt
  app/src/main/java/com/example/bikini_android/ui/settings/SettingsFragment.kt
  app/src/main/java/com/example/bikini_android/util/ktx/AutoClearedValueExt.kt
  gradle.properties
  libraries.gradle
Labels: refactor

#140 [#91] post feed
  app/src/main/java/com/example/bikini_android/app/TestConstants.kt
  app/src/main/java/com/example/bikini_android/network/request/param/RestApiParameterKey.kt
  app/src/main/java/com/example/bikini_android/network/request/param/SampleParameter.kt
  app/src/main/java/com/example/bikini_android/network/request/service/FeedService.kt
  app/src/main/java/com/example/bikini_android/network/request/service/ImagesService.kt
  app/src/main/java/com/example/bikini_android/network/response/ImagesResponse.kt
  app/src/main/java/com/example/bikini_android/repository/feed/Feed.kt
  app/src/main/java/com/example/bikini_android/repository/feed/FeedRepository.kt
  app/src/main/java/com/example/bikini_android/repository/feed/FeedRepositoryImpl.kt
  app/src/main/java/com/example/bikini_android/ui/base/BaseActivity.kt
  app/src/main/java/com/example/bikini_android/ui/board/BoardActivity.kt
  app/src/main/java/com/example/bikini_android/ui/board/BoardItemViewModel.kt
  app/src/main/java/com/example/bikini_android/ui/board/BoardViewModel.kt
  app/src/main/java/com/example/bikini_android/ui/board/FeedPostEvent.kt
  app/src/main/java/com/example/bikini_android/ui/databinding/CommonBindingAdapter.kt
  app/src/main/java/com/example/bikini_android/ui/databinding/ImageBindingAdapter.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/FeedItemViewModel.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/LoadAllFeedsUseCase.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/LoadMyFeedsUseCase.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/LoadNearbyFeedsUseCase.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/LoadRankingFeedsUseCase.kt
  app/src/main/java/com/example/bikini_android/ui/map/FeedMarkerItemViewModel.kt
  app/src/main/java/com/example/bikini_android/ui/progress/ProgressItemViewModel.kt
  app/src/main/java/com/example/bikini_android/util/bus/event/ReadExternalStoragePermissionEvent.kt
  app/src/main/java/com/example/bikini_android/util/file/FileUtils.kt
  app/src/main/java/com/example/bikini_android/util/file/ImageConstants.kt
  app/src/main/java/com/example/bikini_android/util/permission/OnPermissionCallback.kt
  app/src/main/java/com/example/bikini_android/util/permission/OnRequestLocationPermissionUseCase.kt
  app/src/main/java/com/example/bikini_android/util/permission/OnRequestReadExternalStoragePermissionUseCase.kt
  app/src/main/java/com/example/bikini_android/util/permission/PermissionUtils.kt
  app/src/main/java/com/example/bikini_android/util/string/StringConstants.kt
  app/src/main/res/drawable/circle_progress.xml
  app/src/main/res/layout/activity_board.xml
  app/src/main/res/layout/activity_main_holder.xml
  app/src/main/res/layout/fragment_bikini_map.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/view_feed_item.xml
  app/src/main/res/layout/view_progress.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 기능
