Repository Basicbug/Bikini_Android, pull requests merged in 2021-07, with the labels that each got.

#165 PRD_URL 주소 변경
  app/src/main/java/com/example/bikini_android/network/NetworkConstants.kt
  app/src/main/res/xml/network_security_config.xml
Labels: hot fix

#167 Feature/#51 sort
  app/src/main/java/com/example/bikini_android/manager/PreferenceManager.kt
  app/src/main/java/com/example/bikini_android/manager/login/LoginManagerProxy.kt
  app/src/main/java/com/example/bikini_android/network/request/service/ImagesService.kt
  app/src/main/java/com/example/bikini_android/repository/feed/Feed.kt
  app/src/main/java/com/example/bikini_android/repository/feed/FeedRepositoryImpl.kt
  app/src/main/java/com/example/bikini_android/sort/SortCriteriaOption.kt
  app/src/main/java/com/example/bikini_android/sort/SortCriteriaProvider.kt
  app/src/main/java/com/example/bikini_android/sort/SortExtension.kt
  app/src/main/java/com/example/bikini_android/sort/SortFeedCriteriaProvider.kt
  app/src/main/java/com/example/bikini_android/sort/SortFeedExecutor.kt
  app/src/main/java/com/example/bikini_android/sort/SortTarget.kt
  app/src/main/java/com/example/bikini_android/sort/SortType.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/LoadAllFeedsUseCase.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/LoadMyFeedsUseCase.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/LoadNearbyFeedsUseCase.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/LoadRankingFeedsUseCase.kt
  app/src/main/java/com/example/bikini_android/ui/login/LoginViewModel.kt
  app/src/main/java/com/example/bikini_android/util/rx/DefaultSchedulerProvider.kt
  app/src/main/java/com/example/bikini_android/util/rx/SchedulerProvider.kt
  app/src/main/java/com/example/bikini_android/util/rx/TestSchedulerProvider.kt
  app/src/test/java/com/example/bikini_android/LoginViewModelTest.kt
Labels: 2.0.0

#169 #168 그룹핑 피드 클릭시 화면에 렌더링된 모든 피드가 피드리스트 페이지에 그려지는 현상 수정
  app/src/main/java/com/example/bikini_android/ui/feeds/FeedsEvent.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/FeedsFragment.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/LoadAllFeedsUseCase.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/LoadMyFeedsUseCase.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/LoadNearbyFeedsUseCase.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/LoadRankingFeedsUseCase.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/viewmodel/FeedsViewModel.kt
  app/src/main/java/com/example/bikini_android/ui/map/BikiniMapFragment.kt
  app/src/main/java/com/example/bikini_android/ui/profile/ProfileFragment.kt
Labels: 2.0.0, bug

#171 #170 피드 마커 안쪽으로 피드 이미지가 그려지도록 수정
  app/src/main/res/values/dimens.xml
Labels: 2.0.0, bug

#174 Refactor #173 dialog
  app/src/debug/java/com/example/bikini_android/ui/settings/DeveloperSettingImpl.kt
  app/src/debug/java/com/example/bikini_android/ui/settings/SettingsApiFragment.kt
  app/src/debug/java/com/example/bikini_android/ui/settings/SettingsItemProviderImpl.kt
  app/src/main/java/com/example/bikini_android/app/AppResources.kt
  app/src/main/java/com/example/bikini_android/app/BikiniApp.kt
  app/src/main/java/com/example/bikini_android/app/SnackbarHelper.kt
  app/src/main/java/com/example/bikini_android/app/ToastHelper.kt
  app/src/main/java/com/example/bikini_android/manager/PreferenceManager.kt
  app/src/main/java/com/example/bikini_android/manager/login/LoginManagerProxy.kt
  app/src/main/java/com/example/bikini_android/manager/login/naver/NaverLoginManager.kt
  app/src/main/java/com/example/bikini_android/ui/base/BaseMapFragment.kt
  app/src/main/java/com/example/bikini_android/ui/dialog/DialogController.kt
  app/src/main/java/com/example/bikini_android/ui/feeds/FeedVerticalItemViewModel.kt
  app/src/main/java/com/example/bikini_android/ui/holder/MainHolderActivity.kt
  app/src/main/java/com/example/bikini_android/ui/settings/SettingsItemsProvider.kt
  app/src/main/java/com/example/bikini_android/ui/settings/image/SettingsImageCompressionConfigItemProvider.kt
  app/src/main/java/com/example/bikini_android/ui/settings/image/SettingsImageConfigItemProvider.kt
  app/src/main/java/com/example/bikini_android/ui/splash/SplashActivity.kt
  app/src/main/java/com/example/bikini_android/util/format/AbbreviationUtils.kt
  app/src/main/java/com/example/bikini_android/util/permission/PermissionUtils.kt
  app/src/main/res/values/strings.xml
Labels: 2.0.0, refactor
